config/routes.rb
Rails.application.routes.draw do
  root to: "pokemons#index"
  resources :pokemons, only: [:show, :index] do
    resources :pokeballs, only: [:create]
  end

  resources :trainers, only: [:index, :show, :new, :create]
  resources :pokeballs, only: [:show, :destroy]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :trainer
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs
  has_many :trainers, through: :pokeballs
  has_one_attached :photo
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_one_attached :photo
  has_many :pokeballs
  has_many :pokemons, through: :pokeballs
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @pokeball = Pokeball.new(pokeball_params)
    @pokeball.pokemon = @pokemon
    if @pokeball.save
      redirect_to trainer_path(@pokeball.trainer), notice: "You caught this Pokémon!"
    else
      puts @pokeball.errors.full_messages
      render "pokemons/show", status: :unprocessable_entity
    end
  end

  def destroy
    @pokeball = Pokeball.find(params[:id])
    @pokeball.destroy
    redirect_to trainers_path, status: :see_other
  end

  private

  def pokeball_params
    params.require(:pokeball).permit(:trainer_id, :location, :caught_on)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @pokeball = Pokeball.new
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
    @pokeballs = @trainer.pokeballs
  end

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      redirect_to trainers_path, notice: "You created a trainer!"
    else
      puts @trainer.errors.full_messages
      render "trainers", status: :unprocessable_entity
    end
  end

  private

  def trainer_params
    params.require(:trainer).permit(:name, :age, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/_pokemon.html.erb
<div class="pokemon-card">
  <%= cl_image_tag pokemon.photo.key %>
  <h2><%= link_to pokemon.name, pokemon %></h2>
  <span class="element-type"><%= pokemon.element_type %></span>
</div>

app/views/pokemons/index.html.erb
<div class="container">
  <div class="header">
    <h1>Pokédex</h1>
    <%= link_to "Trainers", trainers_path %>
  </div>
  <div class="grid">
	  <% @pokemons.each do |pokemon| %>
	    <%= render pokemon %>
	  <% end %>
   </div>
</div>

app/views/pokemons/show.html.erb
<div class="container">
  <div class="header">
    <%= link_to "< Pokédex", root_path, class: "mb-3"%>
  </div>
  <div class="two-columns">
    <div class="pokemon-details">
      <p>You hear a rustle in the tall grass... A wild Pokémon appears!</p>
      <%= render @pokemon %>
    </div>
    <div>
      <h2>Do you dare to catch this Pokémon?</h2>
      <%= simple_form_for [@pokemon, @pokeball] do |f| %>
        <%= f.association :trainer, label: "Who's trying their luck?" %>
        <%= f.input :location, label: "Where are you?" %>
        <%= f.input :caught_on, html5: true, label: "When?" %>
        <%= f.submit "Catch!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/trainers/_trainer.html.erb
<div class="trainer-card">
  <%= cl_image_tag trainer.photo.key %>
  <h2><%= link_to trainer.name, trainer %></h2>
  <p class="age"><%= trainer.age %> years old</p>
  <%= link_to "", trainer, class: "trainer-card-link" %>
</div>

app/views/trainers/index.html.erb
<div class="container">
  <div class="header">
    <%= link_to "< Pokédex", root_path, class: "mb-3" %>
    <h1>Let's Get Training</h1>
  </div>
  <div class="grid">
    <% @trainers.each do |trainer| %>
      <%= render trainer %>
    <% end %>
  </div>
  <%= link_to "New Trainer", new_trainer_path, class: "btn poke-btn mt-5"%>
</div>

app/views/trainers/new.html.erb
<div class="container">
  <%= link_to "< All Trainers", trainers_path %>
  <div class="header">
    <h1>Create your trainer!</h1>
  </div>
    <div>
      <h2>Do you dare to catch this Pokémon?</h2>
      <%= simple_form_for @trainer do |f| %>
        <%= f.input :name, label: "What's your namek?" %>
        <%= f.input :age, label: "How old are you?" %>
        <%= f.input :photo %>
        <%= f.submit "Create!", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>

app/views/trainers/show.html.erb
<div class="container">
  <header class="header">
  <%= link_to "< Trainers", trainers_path %>
  <h1><%= @trainer.name %> is going to catch 'em all!</h1>
</header>
<div class="two-columns">
  <div class="trainer-details">
    <%= render @trainer %>
  </div>
  <% if @trainer.pokeballs.exists? %>
    <div class="grid">
      <% @trainer.pokeballs.each do |pokeball| %>
        <div class="pokemon-card">
          <%= cl_image_tag pokeball.pokemon.photo.key %>
          <h2><%= link_to pokeball.pokemon.name, pokeball.pokemon %></h2>
          <span class="element-type"><%= pokeball.pokemon.element_type %></span>
          <p>caught on <%= pokeball.caught_on.strftime("%B %d, %Y") %> at <%= pokeball.location %></p>
          <%= link_to "", pokemon_path(pokeball.pokemon), class: "pokemon-card-link" %>
          <%= link_to "Release", pokeball, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-secondary">This trainer has no Pokémon yet. They should get training!</p>
  <% end %>
  </div>
</div>